baseURL = "https://finnpic.org/"
languageCode = "en-us"
title = "FinnPic open source project"
theme = "ananke"

[menu]
[[menu.main]]
identifier="api"
name="API documentation"
url="/api-docs/org/finnpic"
weight=20

[markup.goldmark.renderer]
unsafe= true

# Note: Test reports are disabled while waiting for
# ScalaTest 3.1.0 to support test reports again.
# - vpeurala, 23.12.2019
#
# [[menu.main]]
# identifier="test"
# name="Test report"
# url="/test-report/"
# weight=40

[[menu.main]]
identifier="coverage"
name="Test coverage report"
url="/coverage-report/"
weight=80

[[menu.main]]
identifier="github"
name="GitHub project"
url="https://github.com/orangitfi/finnpic"
weight=100
