name: sbt-coverage

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Instrument for coverage measurement
        run: sbt coverage
      - name: Run the tests
        run: sbt test
      - name: Create a report
        run: sbt coverageReport
      - uses: actions/upload-artifact@v1
        with:
          name: test-report
          path: target/test-report
      - uses: actions/upload-artifact@v1
        with:
          name: coverage-report
          path: target/scala-2.13/scoverage-report
